# Generated by Django 2.2.1 on 2019-05-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20190515_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='pet',
            field=models.BooleanField(default=True),
        ),
    ]
