# Generated by Django 2.2.1 on 2019-05-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20190515_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address1',
        ),
    ]
